# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UlRcKZ6QBWC9DSKRsRR8A2rVPT59UeN
"""

pip install tensorflow

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.optimizers import SGD
from sklearn.datasets import make_moons

x,y=make_moons(n_samples=100,noise=0.30,random_state=42)

model=Sequential([Input(shape=(2,)),
                  Dense(16,activation='relu'),
                  Dense(16,activation='relu'),
                  Dense(1,activation='sigmoid')])

model.compile(loss='binary_crossentropy',
              optimizer=SGD(learning_rate=0.5),metrics=['accuracy'])

model.fit(x,y,epochs=200,batch_size=len(x),verbose=0)

model.fit(x,y,epochs=200,batch_size=16,verbose=1)