# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DB-IzR8YNXb9GsV_WkoydDe0-xhxV-vy
"""

import numpy as np

pip install tensorflow

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
#XOR
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[0]])

#BUILD THE MLP MODEL
model=Sequential()
model.add(Dense(8,input_dim=2,activation="relu"))
model.add(Dense(1,activation="sigmoid"))
#COMPILE THE MODEL(COMPUTE LOSS)
model.compile(loss="binary_crossentropy",optimizer=SGD(learning_rate=0.1),metrics=['accuracy'])
#TRAIN THE MODEL(FP)
model.fit(x,y,epochs=1000,verbose=0)

_,accuracy=model.evaluate(x,y)
print(f"Model Accuracy:{accuracy *100:.2f}%")


predictions=model.predict(x)
print("Predictions:")
print(np.round(predictions))
